language: node_js
node_js:
  - node

dist: bionic
sudo: required

notifications:
  email:
    recipients:
      - louis@s0rs.net
    on_success: always
    on_failure: always
branches:
  only:
   - development
before_script:
  - npm install -g @angular/cli
  - npm install -g now
script:
  - ng build --prod --base-href https://kuroneko420.github.io/bitcoin-order-app/
  
deploy:
  provider: pages
  skip_cleanup: true
  github_token: 64be359981a1d31943d01c7cb380f31a78bbe1c8
  local_dir: dist/bitcoin
  edge: true
  on:
    branch: development
